name: route_finder
description: "A route finder app based on POI's."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  flutter_secure_storage: ^9.2.4
  google_maps_flutter: ^2.13.1
  geolocator: ^14.0.2
  permission_handler: ^12.0.1
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  go_router: ^16.2.5
  cached_network_image: ^3.4.1
  lottie: ^3.3.2
  flutter_polyline_points: ^3.1.0
  flutter_local_notifications: ^19.5.0
  lucide_icons: ^0.257.0
  lucide_icons_flutter: ^3.1.4
  toastification: ^3.0.3
  http: ^1.5.0
  cloud_functions: ^6.0.4
  flutter_card_swiper: ^7.2.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.3
  adaptive_dialog: ^2.6.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
    - .env
  
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
